services:
  - type: web
    name: ledger-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        value: d618ee715c4b523f6bf4c5c7f1057e5a2500dc80fe72dbd01e702e6a2026c478

  - type: web
    name: ledger-frontend
    env: static
    buildCommand: cd frontend && npm install && DISABLE_ESLINT_PLUGIN=true npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: REACT_APP_API_URL
        value: https://ledger-rppg.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
